# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t token

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -lebedev_alexander@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="6f2cdeef-2edc-4f7c-8ad2-1a10f2bbc45f"